"use client";

interface UserAnswer {
  id: string;
  questionId: string;
  userAnswerText: string;
  aiFeedback: string;
  score: number;
}

interface Question {
  id: string;
  questionText: string;
  aiAnswer: string;
  difficulty?: string;
}

interface QuestionWithAnswer extends Question {
  userAnswer: UserAnswer | null;
}

interface ExportButtonProps {
  items: QuestionWithAnswer[];
  jobRole: string;
  techStack: string;
  experienceLevel: string;
  interviewDate: string;
  userName: string;
}

export default function ExportButton({
  items,
  jobRole,
  techStack,
  experienceLevel,
  interviewDate,
  userName,
}: ExportButtonProps) {
  const handleExport = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ format: "a4", orientation: "portrait" });

    const PW = 210;
    const MG = 20;
    const CW = 170;
    const CONTENT_MAX = 278;
    const FOOTER_Y = 285;

    const hx = (hex: string): [number, number, number] => {
      const h = hex.replace("#", "");
      return [
        parseInt(h.slice(0, 2), 16),
        parseInt(h.slice(2, 4), 16),
        parseInt(h.slice(4, 6), 16),
      ];
    };
    const tc = (hex: string) => {
      const [r, g, b] = hx(hex);
      doc.setTextColor(r, g, b);
    };
    const dc = (hex: string) => {
      const [r, g, b] = hx(hex);
      doc.setDrawColor(r, g, b);
    };
    const fc = (hex: string) => {
      const [r, g, b] = hx(hex);
      doc.setFillColor(r, g, b);
    };

    const fmtDate = (ds: string) => {
      const d = new Date(ds || Date.now());
      return isNaN(d.getTime())
        ? new Date().toLocaleDateString("en-GB", {
            day: "2-digit",
            month: "short",
            year: "numeric",
          })
        : d.toLocaleDateString("en-GB", {
            day: "2-digit",
            month: "short",
            year: "numeric",
          });
    };

    // Reusable header block drawn on every page
    const drawHeader = () => {
      fc("#0a0a0b");
      doc.rect(0, 0, PW, 38, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(20);
      tc("#d4a03a");
      doc.text("WHISPR", 20, 14);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      tc("#f0ede8");
      doc.text("Interview Feedback Summary", 20, 22);
      dc("#d4a03a");
      doc.line(0, 38, PW, 38);
    };

    const drawFooter = (page: number, total: number) => {
      dc("#d4a03a");
      doc.line(MG, FOOTER_Y - 4, PW - MG, FOOTER_Y - 4);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      tc("#aaaaaa");
      doc.text("Generated by Whispr", MG, FOOTER_Y);
      doc.text(`Page ${page} of ${total}`, PW - MG, FOOTER_Y, {
        align: "right",
      });
    };

    // Overall score: average of parsed aiFeedback.score for non-skipped
    const nonSkipped = items.filter((i) => i.userAnswer !== null);
    let overallScoreStr = "N/A";
    if (nonSkipped.length > 0) {
      let total = 0;
      for (const item of nonSkipped) {
        let s = 0;
        try {
          const p = JSON.parse(item.userAnswer!.aiFeedback) as {
            score?: unknown;
          };
          s = Number(p.score) || 0;
        } catch {
          s = 0;
        }
        total += s;
      }
      overallScoreStr = (total / nonSkipped.length).toFixed(1);
    }

    // ── PAGE 1 HEADER ────────────────────────────────────────────────────
    drawHeader();

    // Session info (below the dark header block)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    tc("#1a1a1a");
    doc.text(userName, 20, 46);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    tc("#333333");
    doc.text(
      [jobRole, experienceLevel, techStack].filter(Boolean).join(" | ") || "—",
      20,
      53
    );

    tc("#666666");
    const skippedCount = items.length - nonSkipped.length;
    doc.text(
      `${fmtDate(interviewDate)} | Total Questions: ${items.length} | Answered: ${nonSkipped.length} | Skipped: ${skippedCount}`,
      20,
      59
    );

    // ── OVERALL SCORE ────────────────────────────────────────────────────
    let y = 67;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    tc("#d4a03a");
    doc.text("OVERALL SCORE", MG, y);
    y += 5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    tc("#1a1a1a");
    doc.text(overallScoreStr, MG, y);

    if (overallScoreStr !== "N/A") {
      const scoreW = doc.getTextWidth(overallScoreStr);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      tc("#666666");
      doc.text(" /10", MG + scoreW, y);
    }
    y += 11;

    // ── QUESTION BREAKDOWN LABEL ─────────────────────────────────────────
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    tc("#d4a03a");
    doc.text("QUESTION BREAKDOWN", MG, y);
    y += 5;

    // Column layout: # (10mm) | Question (90mm) | Score (15mm) | Gap (55mm)
    const X_NUM = MG;        // 20 — left edge of # col
    const X_QT = MG + 10;    // 30 — left edge of question col
    const X_SCORE_R = MG + 115; // 135 — right edge of score col (right-aligned)
    const X_GAP = MG + 115;  // 135 — left edge of gap col

    // ── COLUMN HEADERS ───────────────────────────────────────────────────
    const HDR_H = 7;

    const drawColHeaders = (yPos: number) => {
      fc("#0a0a0b");
      doc.rect(MG, yPos, CW, HDR_H, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      tc("#f0ede8");
      doc.text("#", X_NUM + 1, yPos + 5);
      doc.text("QUESTION", X_QT + 1, yPos + 5);
      doc.text("SCORE", X_SCORE_R, yPos + 5, { align: "right" });
      doc.text("KEY GAP", X_GAP + 2, yPos + 5);
    };

    drawColHeaders(y);
    y += HDR_H;

    // ── DATA ROWS ────────────────────────────────────────────────────────
    items.forEach((item, idx) => {
      // Parse aiFeedback
      let parsedScore = 0;
      let gapText = "";
      if (item.userAnswer?.aiFeedback) {
        try {
          const p = JSON.parse(item.userAnswer.aiFeedback) as {
            score?: unknown;
            gaps?: unknown[];
          };
          parsedScore = Number(p.score) || 0;
          if (Array.isArray(p.gaps) && p.gaps.length > 0) {
            gapText = String(p.gaps[0]);
          }
        } catch {
          // defaults stay
        }
      }

      // Wrap question text to question col width (90mm)
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const qLines = doc.splitTextToSize(item.questionText, 90) as string[];

      // Wrap gap text to gap col width (52mm), max 2 lines
      doc.setFontSize(7);
      const gapLines = (doc.splitTextToSize(gapText, 52) as string[]).slice(
        0,
        2
      );

      const rowH = Math.max(8, qLines.length * 5);

      // Page overflow: add new page if row won't fit
      if (y + rowH > CONTENT_MAX) {
        doc.addPage();
        drawHeader();
        y = 44;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        tc("#d4a03a");
        doc.text("QUESTION BREAKDOWN (continued)", MG, y);
        y += 5;
        drawColHeaders(y);
        y += HDR_H;
      }

      const rowTop = y;
      const textY = rowTop + 5;

      // Alternating row backgrounds
      fc(idx % 2 === 0 ? "#ffffff" : "#f7f5f0");
      doc.rect(MG, rowTop, CW, rowH, "F");

      // # column
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      tc("#888888");
      doc.text(String(idx + 1), X_NUM + 1, textY);

      // Question text (wrapped)
      tc("#1a1a1a");
      qLines.forEach((line, li) => {
        doc.text(line, X_QT, textY + li * 5);
      });

      // Score column
      if (item.userAnswer) {
        const qs = parsedScore;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        tc(qs >= 7 ? "#16a34a" : qs >= 4 ? "#d4a03a" : "#dc2626");
        doc.text(qs.toFixed(1), X_SCORE_R, textY, { align: "right" });
      } else {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        tc("#aaaaaa");
        doc.text("SKIP", X_SCORE_R, textY, { align: "right" });
      }

      // Gap column (wrapped, ≤2 lines)
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      tc("#666666");
      gapLines.forEach((line, li) => {
        doc.text(line, X_GAP + 2, textY + li * 5);
      });

      // Row bottom border
      dc("#e5e5e5");
      doc.line(MG, rowTop + rowH, MG + CW, rowTop + rowH);

      y += rowH;
    });

    // ── FOOTERS (all pages) ──────────────────────────────────────────────
    const totalPgs = doc.getNumberOfPages();
    for (let p = 1; p <= totalPgs; p++) {
      doc.setPage(p);
      drawFooter(p, totalPgs);
    }

    // ── SAVE ─────────────────────────────────────────────────────────────
    let dateSlug: string;
    try {
      dateSlug = new Date(interviewDate || Date.now())
        .toISOString()
        .split("T")[0];
    } catch {
      dateSlug = new Date().toISOString().split("T")[0];
    }
    const roleSlug = (jobRole || "interview")
      .toLowerCase()
      .replace(/\s+/g, "-");
    doc.save(`whispr-feedback-${roleSlug}-${dateSlug}.pdf`);
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-2 border border-white/[0.12] text-[#7a7870] hover:text-[#f0ede8] text-xs uppercase tracking-[0.1em] px-5 py-2 transition-colors flex-shrink-0 mt-1"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      Export Summary
    </button>
  );
}
